---
title: "随机变量"
author: "limbo"
date: "5/29/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 随机变量

### 读取数据

```{r read data}
setwd("~/Documents/R_and_statics/statics/")
dat <- read.csv("femaleMiceWeights.csv")
```

### 查看前几行
```{r head}
head(dat)
```

### 计算不同平均值

```{r mean}
library(dplyr)

control <- dat %>% 
  filter(Diet == "chow") %>%   
  select(Bodyweight) %>% 
  unlist()

treatment <- dat %>% 
  filter(Diet == "hf") %>%     
  select(Bodyweight) %>% 
  unlist()

mean(treatment)
mean(control)


obsdiff <- mean(treatment) - mean(control)
print(obsdiff)
```
### 随机变量
#### 下载数据
```{r download female weight data}
library(downloader)
url <- "https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/femaleControlsPopulation.csv"
filename <- "femaleControlsPopulation.csv"
if (!file.exists(filename)) download(url,destfile=filename)
population <- read.csv(filename)
population <- unlist(population) # turn it into a numeric
```
#### 抽样12 mice
```{r}
control <- sample(population, 12)
mean(control)
```
### The Null Hypothesis
#### 12 control mice
```{r}
control <- sample(population, 12)
```
#### another 12 control mice that we act as if they were not 
```{r}
treatment <- sample(population, 12)
print(mean(treatment) - mean(control))
```
#### do it 10000 times "for-loop"
```{r}
n <- 10000
null <- vector("numeric", n)
for (i in 1:n) {
  control <- sample(population, 12)
  treatment <- sample(population, 12)
  null[i] <- mean(treatment) - mean(control)
}
```
#### 比较`null`大于等于`obsdiff`的比例
```{r}
mean(null >= obsdiff)
```
这就是p值得定义
## Distribution

```{r}
library(UsingR)
x <- father.son$fheight
round(sample(x, 10), 1)# 对其中数据随机选取去10个
```
### 累积分布函数
`cumulative distribution function(CDF)`
```{r}
samllest <- floor(min(x))
largest <- ceiling(max(x))
values <- seq(samllest, largest, len = 300)
heightecdf <- ecdf(x)
plot(values, heightecdf(values), type = "l", xlab = "a (Height in inches)", ylab = "Pr ( x <= a)")
```

s

